### ISSUE TITLE
please provide stand alone maven example to use it

### ISSUE THREAD

**Issue by builderall** [racodond/sonar-gherkin-plugin#51]
Hi,
 Can you please provide a standalone maven example? Or may be provide link to the source code to the demo project?
Thanks much.

**Comment by racodond** [comment]
Hi @builderall,

Could you please detail a bit your needs or your issue? Because Gherkin code can be analyzed as any other language, see https://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner+for+Maven.

I'm not against providing a sample project but I need to know what prevents you from properly and easily analyzing your Gherkin code. So that I can provide an example that brings some added value to the SonarQube documentation.

Thanks

David

**Comment by builderall** [comment]
Hi,

  can you please add a single feature to this, and give maven snippet. I am getting 
error as soon as I invoke:

mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install -Pcoverage-per-test

Results :
Tests in error:
Looks like several tests executed in parallel in the same JVM, thus coverage per test can't be recorded correctly.
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

Also, do I need to add any other dependency or defines gherkin language as a property to publish them to sonar?

source:
https://github.com/SonarSource/sonar-examples/tree/master/projects/languages/java/code-coverage/ut/ut-maven-jacoco

Thanks much.

**Comment by racodond** [comment]
Hi,

Could you please describe what you are trying tout achieve? Your example is about code coverage with JaCoCo. Do you generate à JaCoCo report on your own project? Are you interested in getting issues on your Gherkin code or are you interested in code coverage by your Gherkin feature files?

Thanks

David

**Comment by racodond** [comment]
@builderall You might be interested in https://github.com/racodond/sonar-gherkin-plugin#maven
I'm closing the issue. Feel free to comment if you still face some issues while analyzing your Gherkin code.
