### ISSUE TITLE
Check that .feature files exist in the project

### ISSUE THREAD

**Issue by alexwalker-1993** [racodond/sonar-gherkin-plugin#66]
As a Test Manager I am interesting in 1. checking the quality of the tests being written which this helps with and 2. I want to insure my teams are using cucumber in the first place so a rule that checks that feature files exist would be great

**Comment by racodond** [comment]
Hi @alexwalker-1993,

Could you please detail #2 because I am not sure to understand and I don't see how this would be checked?

Thanks!

David

**Comment by alexwalker-1993** [comment]
Hi David,

I am having trouble with some of my teams deciding not to use cucumber and I was hoping there was a quick way to include it into SonarQube to confirm that .feature files exist that way if my teams are not using cucumber it becomes evident as soon as SonarQube runs against test code

**Comment by racodond** [comment]
Ah OK. You want to know if the project contains at least one .feature file, right? If so, it is not possible because the way SonarQube works is that a plugin is only triggered if the project contains file extensions it can analyze. To find out which projects do not use Cucumber, you can use the SonarQube web API and retrieve number of lines per language and per project. Then you can filter to find out the ones with zero line of cucumber code.

**Comment by alexwalker-1993** [comment]
Okay thanks for your help :)
